apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: docker.io/hhayakaw/skaffold-insider
    workspace: .
  local:
    skipPush: true
deploy:
  kubectl:
    manifests:
      - skaffold-insider.yaml
profiles:
  - name: push
    build:
      local:
        skipPush: false
      tagPolicy:
        gitCommit: {}
